Document: k3s
Title: Debian k3s Manual
Author: <insert document author here>
Abstract: This manual describes what k3s is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/k3s/k3s.sgml.gz

Format: postscript
Files: /usr/share/doc/k3s/k3s.ps.gz

Format: text
Files: /usr/share/doc/k3s/k3s.text.gz

Format: HTML
Index: /usr/share/doc/k3s/html/index.html
Files: /usr/share/doc/k3s/html/*.html
